name: Publish docs

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: libcairo2-dev gir1.2-gtk-4.0 libgirepository1.0-dev
        version: 1
    - run: uv sync --all-extras --dev
    - run: uv run task gendoc
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
